version: '3.8'

services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  habits:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/habits


  celery:
    build: .
    tty: true
    command: sh -c "celery -A config worker -l INFO"
    volumes:
      - .:/habits
    depends_on:
      - db
      - redis
      - habits
    env_file:
      - .env

  celery-beat:
    build: .
    tty: true
    command: sh -c "celery -A config beat -l INFO"
    volumes:
      - .:/habits
    depends_on:
      - db
      - redis
      - habits
    env_file:
      - .env

volumes:
  pg_data:
